# Generated by Django 3.1.4 on 2021-02-09 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ps_blog_app', '0002_userprofileinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='user',
        ),
    ]
